### ISSUE TITLE
[1.16.5 - Forge] Crashes Server on Start-up 

### ISSUE THREAD

**Issue by Foxydapirate12** [Elrol/ServerUtils#1]
I'm currently using Bisecthosting on version 1.16.5, the Forge version is 36.2.39.
Both Version 2.4.4 and Version 2.3.6 crash the game. I at first tried to start the server with version 2.4.4 but it crashed, so i opted to downgrade to version 2.3.6 which worked for a while up until i tried using the signshop, after restarting the server it started crashing on startup. So i tried to use 2.4.4 again to get the crash report for that but after trying multiple times, it repeatedly just caused the server to completely freeze including the console, it also becomes unresponsive to any attempts to stop the server so i've only been able to get the log output before it freezes. I'll provide both the 2.3.6 Crash log and log output of 2.4.4 bellow:
https://gist.github.com/Foxydapirate12/47c46e6d69d6b3f1f148b67d54487be6#file-version-2-3-6-crash-2022-09-10_01-34-26-server-txt
https://gist.github.com/Foxydapirate12/47c46e6d69d6b3f1f148b67d54487be6#file-version-2-4-4-output-before-freeze

**Comment by Foxydapirate12** [comment]
I also tried breaking the sign with the mod removed and then adding it back later, but it still didn't work. And i also tried disabling the economy feature in the config but that didn't work either

**Comment by DaemonUmbra** [comment]
Are you able to provide the world save that produces this error?
